import BannerBox from "@/businessComponents/BannerBox";
import WhyDescBox from "@/businessComponents/whyDescBox";
import MultipleBoxDesc from "@/businessComponents/multipleBoxDesc";
import AppBox from "@/businessComponents/appBox";
import "./index.css";

import bg from "@/assets/social/bg.png";
import bg3 from "@/assets/about_us/bg2.png";
import arrowRight from "@/assets/arrow-right.svg";

export default function Social() {
  const handleGotoContactUs = () => {
    window.location.href = `${window.location.origin}/#/contact`;
  };

  const handleClick = () => {
    window.location.href = `${window.location.origin}/#/contact`;
  };

  const bannerBoxProps = {
    title: "Social Media Marketing",
    description: "",
    bgImg: bg,
    className: "sem-banner-box",
  };

  const multipleBoxDescInfo = {
    title: "OUR STRATEGIC SOCIAL MEDIA MARKETING SERVICES",
    bgColor: "#FBF8F6",
    description: [
      {
        title: "Identify Your Social Media Goals",
        desc: "Be it to increase brand awareness, leads, web traffic or sales, we examine your social media and business objectives and build effective social media plan so as to align all social media strategies.",
        minHeight: 291,
      },
      {
        title: "Hit Target Audience Accurately",
        desc: "In-depth research and surveys are done to convert prospects into customers.",
        minHeight: 291,
      },
      {
        title: "Data Analytics And Reporting",
        desc: "By extracting extensive data and reports generated by 1st and 3rd party analytic tools, our social media experts continuously create, track and optimize your social media campaigns with deep insights.",
        minHeight: 216,
      },
      {
        title: "Social Media Budget Optimization",
        desc: "Taken industry benchmarks into consideration, we comprehensively measure your social media ROI and monitor your bidding strategy so that no money is splashed meaninglessly.",
        minHeight: 216,
      },
      {
        title:
          "<a style='color:#337DB9' href='#/services/content'>Content Management<a/>",
        desc: "Cultural and on-the-ground pieces – built by our localized content team – are distributed to achieve 4.6 billion+ total reach across industries through our 15,000+ media networks in China and Asia through online WOM.",
        minHeight: 216,
      },
      {
        title:
          "<a style='color:#337DB9' href='#/services/influencer'>Influencer Marketing<a/>",
        desc: "<a style='color:#337DB9' href='#/tech-data'>Our AI-driven influencer management platform<a/> – supported by 200,000+ cross-platform influencer data in China and Asia – provides easy management and analytical reports all in one place.",
        minHeight: 216,
      },
    ],
    btnText: "SEE OUR DIGITAL MARKETING FULL SERVICES",
    btnClick: handleClick,
  };

  const whyDescBoxDataList = [
    {
      title: "In-market Social Media Foundation",
      desc: "Upon learning your KPIs, our experienced and dedicated social media marketing specialists identify your most suitable social marketing platforms, refine ad strategies, and increase your social media ROI with close monitoring & insightful data analysis.",
    },
    {
      title: "Total Social Media Marketing Services",
      desc: "Our integrated social media marketing services maximize your social marketing conversions with localized content and influencer management.",
    },
    {
      title: "Up To Speed With Social Media Marketing Trend",
      desc: "We move fast with the latest media assets and social trends in the market so as to secure all potential engagements and sales during ad execution for greatest KPI.",
    },
  ];

  return (
    <section className="min-h-screen  flex flex-col leading-[30px]">
      <BannerBox
        {...bannerBoxProps}
        renderAfterContent={
          <button
            onClick={handleGotoContactUs}
            className="mx-auto mt-90 bg-[#fff] text-[#337DB9] h-36 w-148 rounded-18 font-semibold leading-36 flex flex-row items-center justify-center gap-10 hover:opacity-60"
          >
            Contact Us
            <img src={arrowRight} alt="arrow-right" className="w-10 h-16 " />
          </button>
        }
      />

      <MultipleBoxDesc {...multipleBoxDescInfo} />

      <AppBox
        appList={[
          "youtube",
          "linkedin",
          "tiktok2",
          "weibo",
          "smallredbook",
          "youtube",
          "instagram",
          "facebook",
          "douyin",
          "smallredbook",
          "toutiao",
          "line",
          "twitter",
        ]}
      />

      <WhyDescBox
        title="WHY US AS SOCIAL MEDIA AGENCY?"
        dataList={whyDescBoxDataList}
      />

      <section
        className="w-full py-65 bg-[#fff]"
        style={{ backgroundImage: `url(${bg3})`, backgroundSize: "100% 100%" }}
      >
        <section className="min-box-1180 h-full mx-auto text-center ">
          <div className="w-900 h-full mx-auto">
            <h1 className="wow animate__animated animate__jackInTheBox  font-semibold text-56 text-[#fff] leading-70 ">
              <a href="#/contact">GET FREE CONSULTATION NOW</a>
            </h1>
          </div>
        </section>
      </section>
    </section>
  );
}
