import BannerBox from "@/businessComponents/BannerBox";
import WhyDescBox from "@/businessComponents/whyDescBox";
import MultipleBoxDesc from "@/businessComponents/multipleBoxDesc";
import AppBox from "@/businessComponents/appBox";
import "./index.css";

import bg from "@/assets/sem/bg.png";
import bg3 from "@/assets/about_us/bg2.png";
import arrowRight from "@/assets/arrow-right.svg";

export default function SEM() {
  const handleGotoContactUs = () => {
    window.location.href = `${window.location.origin}/#/contact`;
  };

  const handleClick = () => {
    window.location.href = `${window.location.origin}/#/contact`;
  };

  const bannerBoxProps = {
    title: "Search Engine Marketing (SEM)",
    description: "",
    bgImg: bg,
    className: "sem-banner-box",
  };

  const multipleBoxDescInfo = {
    title: "OUR STRATEGIC SEARCH ENGINE MARKETING SERVICES",
    bgColor: "linear-gradient( 138deg, #F4F8F9 0%, #F1F6F7 100%)",
    description: [
      {
        title: "SEM Campaign Planning & Setup",
        desc: "Gain access to our 200,000+ influencer data across 9 Asian regions on popular platforms like Facebook, Instagram, YouTube, TikTok, XiaoHongShu, Wechat and more, you can discover the perfect influencer for your KOL marketing campaigns across 15+ industries. Our exclusive brand comparison tool enables you to monitor and analyse competitors, ensuring you stay ahead in the market.",
        minHeight: 291,
      },
      {
        title: "SEM Testing & Optimization",
        desc: "Apply ad copy A/B testing to your SEM campaigns and optimize SEM campaigns with our intelligent Search Engine Marketing optimization system and advanced competitor analysis.",
        minHeight: 291,
      },
      {
        title: "Search Shopping Advertising",
        desc: "Apart from SEM text campaigns, search shopping advertising is good fit to E-commerce companies. We use sophisticated data analysis and keyword planner tool to help your products stand out from keen competition.",
        minHeight: 216,
      },
      {
        title: "Landing Page Review & Suggestion",
        desc: "Landing pages are important to the success of an SEM Campaign. An attractive and contented landing page can help you get a higher conversion rate and sales. Our SEM experts' industry-knowhow can give great suggestions.",
        minHeight: 216,
      },
      {
        title: "Timely Data Analysis & Report",
        desc: "By extracting extensive data and reports generated by 1st and 3rd party analytic tools, our SEM experts continuously create, track and optimize your Search Engine Marketing campaigns with deep insights.",
        minHeight: 216,
      },
      {
        title: "Remarketing And Retargeting",
        desc: "Tailor the SEM campaigns to users who have previously visit your website and encourage them to convert.",
        minHeight: 216,
      },
    ],
    btnText: "SEE OUR DIGITAL MARKETING FULL SERVICES",
    btnClick: handleClick,
  };

  const whyDescBoxDataList = [
    {
      title: "Award-Winner With 15+ Years Of Worldwide SEM Knowhow",
      desc: "Our SEM solution reaches over 90% internet users and we manage 100 million+ ad budget in Asia – Hong Kong, China, Taiwan, Thailand, Malaysia, Singapore, and Worldwide. Our certified SEM experts create ad content with localized language and personalized SEM strategy for different industries – Ecommerce, Gaming, Education, IT, Finance, Travel, FMCG, Beauty, Health products, etc.",
    },
    {
      title: "Performance- & Data-Driven SEM Strategy",
      desc: "We know your potential customers’ behaviors, keywords they search and ad text that encourages them to convert with sophisticated data analysis and keyword planner tool. From keyword selection, ad text, audience to bid metric, we ensure you better ROI and acquire more customers in Asia & overseas.",
    },
    {
      title: "Market Insights & 24/7 Optimization (Centaurus Ad)",
      desc: "Empower your search campaign with our intelligent Search Engine Marketing optimization system (<a style='color:#337DB9' href='#/tech-data'>Centaurus Ad<a/>) and advanced competitor analysis tool to ensure your ad is always on top of the search result page (Google, Yahoo, Bing, Baidu, Naver and Yandex) with lower cost.",
    },
  ];

  return (
    <section className="min-h-screen  flex flex-col leading-[30px]">
      <BannerBox
        {...bannerBoxProps}
        renderAfterContent={
          <button
            onClick={handleGotoContactUs}
            className="mx-auto mt-90 bg-[#fff] text-[#337DB9] h-36 w-148 rounded-18 font-semibold leading-36 flex flex-row items-center justify-center gap-10 hover:opacity-60"
          >
            Contact Us
            <img src={arrowRight} alt="arrow-right" className="w-10 h-16" />
          </button>
        }
      />

      <MultipleBoxDesc {...multipleBoxDescInfo} />

      <AppBox
        appList={["google", "baidu", "yahoo", "bing", "yandex", "naver"]}
      />

      <WhyDescBox
        title="WHY US AS SEARCH ENGINE MARKETING AGENCY?"
        dataList={whyDescBoxDataList}
      />

      <section
        className="w-full py-65 bg-[#fff]"
        style={{ backgroundImage: `url(${bg3})`, backgroundSize: "100% 100%" }}
      >
        <section className="min-box-1180 h-full mx-auto text-center ">
          <div className="w-900 h-full mx-auto">
            <h1 className="wow animate__animated animate__jackInTheBox  font-semibold text-56 text-[#fff] leading-70 ">
              <a href="#/contact">GET FREE CONSULTATION NOW</a>
            </h1>
          </div>
        </section>
      </section>
    </section>
  );
}
